// 마린시티 식당 데이터 (2025.11.18 기준)
// 가격 단위: 만원
const RESTAURANTS = [
  { name: "창가자미",          loc: "골든머르시아",          type: "한식",   menu: "미역국, 물회",              price: 2.0 },
  { name: "해윤대대박",        loc: "골든머르시아",          type: "한식",   menu: "곰탕, 해장국",              price: 1.6 },
  { name: "사마정",            loc: "골든머르시아",          type: "아시아", menu: "샤브샤브",                  price: 1.6 },
  { name: "윤식당차돌박이",    loc: "골든스위트",            type: "한식",   menu: "차돌박이접심세트",          price: 2.2 },
  { name: "베비장보쌈",        loc: "대우마리나",            type: "한식",   menu: "보쌈",                      price: 1.8 },
  { name: "어반스시",          loc: "대우마리나2차",         type: "아시아", menu: "스시",                      price: 1.2 },
  { name: "도다지",            loc: "대우월드마크해운대",    type: "한식",   menu: "소불고기, 두루치기정식",    price: 1.4 },
  { name: "국밥미조",          loc: "대우월드마크해운대",    type: "한식",   menu: "돼지국밥",                  price: 0.9 },
  { name: "라호짬뽕",          loc: "대우월드마크해운대",    type: "아시아", menu: "짬뽕",                      price: 1.0 },
  { name: "할매손충무김밥",    loc: "대우트럼프월드마린",    type: "분식",   menu: "충무김밥",                  price: 0.7 },
  { name: "바르다김선생",      loc: "대우트럼프월드마린",    type: "분식",   menu: "김밥 등",                   price: 0.8 },
  { name: "오니기리와이규동",  loc: "대우트럼프월드마린",    type: "분식",   menu: "오니기리 및 규동",          price: 0.7 },
  { name: "풍원장미역국",      loc: "더샵아델리스",          type: "한식",   menu: "미역국정찬",                price: 1.6 },
  { name: "이레욱",            loc: "더샵아델리스",          type: "한식",   menu: "곰탕, 해장국",              price: 1.7 },
  { name: "씨엘로",            loc: "더샵아델리스",          type: "양식",   menu: "파스타, 피자 등",           price: 1.8 },
  { name: "캥거루포인트",      loc: "더샵아델리스",          type: "양식",   menu: "파스타, 피자 등",           price: 1.8 },
  { name: "피제리아라르도",    loc: "더샵아델리스",          type: "양식",   menu: "피자 등",                   price: 1.8 },
  { name: "못난이식당",        loc: "두산위브",              type: "한식",   menu: "갈치구이, 갈치찌개",        price: 5.5 },
  { name: "오토김밥",          loc: "마린파크",              type: "분식",   menu: "김밥 닭강정 라면",          price: 1.0 },
  { name: "프랭크버거",        loc: "마린파크",              type: "양식",   menu: "햄버거 등",                 price: 0.8 },
  { name: "맘스터치",          loc: "마린파크",              type: "양식",   menu: "햄버거 등",                 price: 0.8 },
  { name: "오복식당",          loc: "선프라자",              type: "한식",   menu: "제육볶음, 삼겹살정식",      price: 0.8 },
  { name: "재주카까워차린식탁",loc: "선프라자",              type: "한식",   menu: "집밥",                      price: 0.9 },
  { name: "한옥집",            loc: "선프라자",              type: "한식",   menu: "비빔밥",                    price: 0.8 },
  { name: "친정엄마",          loc: "선프라자",              type: "분식",   menu: "김밥, 라면 등",             price: 0.7 },
  { name: "장금이국수",        loc: "아이파크",              type: "한식",   menu: "국수",                      price: 0.6 },
  { name: "풍원장고막",        loc: "아이파크",              type: "한식",   menu: "꼬막정찬",                  price: 2.0 },
  { name: "어보",              loc: "아이파크",              type: "한식",   menu: "모듬 생선구이",             price: 1.8 },
  { name: "동백삼계탕",        loc: "오렌지프라자",          type: "한식",   menu: "삼계탕, 닭도리탕",          price: 1.7 },
  { name: "전주남문순댓국",    loc: "오렌지프라자",          type: "한식",   menu: "순대국밥",                  price: 1.0 },
  { name: "마라섬",            loc: "오렌지프라자",          type: "한식",   menu: "마라탕",                    price: 1.0 },
  { name: "마린돈까스",        loc: "오렌지프라자",          type: "양식",   menu: "돈까스 메밀",               price: 1.0 },
  { name: "웨밀집",            loc: "오렌지프라자",          type: "한식",   menu: "돈까스 메밀",               price: 1.5 },
  { name: "유가솜씨",          loc: "오렌지프라자",          type: "한식",   menu: "닭갈비",                    price: 0.9 },
  { name: "메이친",            loc: "오렌지프라자",          type: "아시아", menu: "중식",                      price: 1.3 },
  { name: "카페리본",          loc: "자이상가",              type: "양식",   menu: "샌드위치",                  price: 0.9 },
  { name: "훈식당",            loc: "자이상가",              type: "한식",   menu: "집밥",                      price: 1.0 },
  { name: "락앤웜",            loc: "자이상가",              type: "아시아", menu: "중식",                      price: 1.2 },
  { name: "리홍",              loc: "제니스",                type: "한식",   menu: "집밥",                      price: 1.2 },
  { name: "구룡포해녀전복",    loc: "제니스",                type: "한식",   menu: "미역국",                    price: 1.5 },
  { name: "겟201",             loc: "제니스",                type: "양식",   menu: "파스타, 피자 등",           price: 1.5 },
  { name: "강가네손만두",      loc: "제니스",                type: "분식",   menu: "만두 및 돈까스",            price: 0.9 },
  { name: "고봉민김밥",        loc: "제니스",                type: "분식",   menu: "김밥 등",                   price: 0.9 },
  { name: "우봉",              loc: "하이페리온",            type: "아시아", menu: "샤브샤브, 소고기 구이",     price: 1.9 },
  { name: "담동대구뼈찜아구찜",loc: "한일오르듀",            type: "한식",   menu: "아구찜",                    price: 4.3 },
  { name: "버거앤파스타",      loc: "한일오르듀",            type: "양식",   menu: "햄버거, 파스타 등",         price: 1.5 },
  { name: "호아빈",            loc: "한일오르듀",            type: "아시아", menu: "베트남쌀국수",              price: 1.2 },
  { name: "거대곰탕",          loc: "현대베네시티",          type: "한식",   menu: "곰탕",                      price: 1.7 },
  { name: "치즈치즈치즈",      loc: "현대카멜리아",          type: "양식",   menu: "파스타, 뇨끼 등",           price: 1.5 },
];
